/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bruzga.antanas.mokesciai;

import java.awt.Color;
import static java.lang.Double.parseDouble;

/**
 *
 * @author tony
 */
public class Mokesciai extends javax.swing.JFrame {

    /**
     * Creates new form Mokesciai
     */
    public Mokesciai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        Mokesciai = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Kvadratura1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Kvadratura2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Kvadratura3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Kvadratura4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        paslaugosMokestis = new javax.swing.JTextField();
        dujuKuboKaina = new javax.swing.JTextField();
        dujuPrinaudota = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SkaiciuotiBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        kvadratura1ResDujos = new javax.swing.JTextField();
        kvadratura2ResDujos = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        kvadratura3ResDujos = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        kvadratura4ResDujos = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        resDujosTotal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        elektraTotal = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        vanduoTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        kvadratura1Total = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        kvadratura3Total = new javax.swing.JTextField();
        kvadratura4Total = new javax.swing.JTextField();
        kvadratura2Total = new javax.swing.JTextField();
        dujosElektraVanduoTotal = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();

        jLabel13.setText("jLabel13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Kvadratura1");

        Kvadratura1.setEditable(false);
        Kvadratura1.setBackground(new java.awt.Color(215, 215, 215));
        Kvadratura1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
       // Kvadratura1.setText("10"); //plotai_kambariu = [9.93, 15.69, 16.44, 22.65]
        Kvadratura1.setText("9.93"); //plotai_kambariu = [9.93, 15.69, 16.44, 22.65]

        Kvadratura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kvadratura1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Kvadratura2");

        Kvadratura2.setEditable(false);
        Kvadratura2.setBackground(new java.awt.Color(215, 215, 215));
        Kvadratura2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
//        Kvadratura2.setText("17");
        Kvadratura2.setText("15.69");
        Kvadratura2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kvadratura2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Kvadratura3");

        Kvadratura3.setEditable(false);
        Kvadratura3.setBackground(new java.awt.Color(215, 215, 215));
        Kvadratura3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
//        Kvadratura3.setText("18");
        Kvadratura3.setText("16.44");
        Kvadratura3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kvadratura3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Kvadratura4");

        Kvadratura4.setEditable(false);
        Kvadratura4.setBackground(new java.awt.Color(215, 215, 215));
        Kvadratura4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
//        Kvadratura4.setText("24");
        Kvadratura4.setText("22.65");
        Kvadratura4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kvadratura4ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Paslaugos Mokestis:");

        paslaugosMokestis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        paslaugosMokestis.setText("3.99");
        paslaugosMokestis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paslaugosMokestisActionPerformed(evt);
            }
        });

        dujuKuboKaina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dujuKuboKaina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dujuKuboKainaActionPerformed(evt);
            }
        });

        dujuPrinaudota.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dujuPrinaudota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dujuPrinaudotaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Duju Kubo Kaina:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Prinaudojo Duju:");

        SkaiciuotiBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SkaiciuotiBtn.setText("Skaiciuoti");
        SkaiciuotiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SkaiciuotiBtnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Kvadratura1  Dujos:");

        kvadratura1ResDujos.setEditable(false);
        kvadratura1ResDujos.setBackground(new java.awt.Color(215, 215, 215));
        kvadratura1ResDujos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kvadratura1ResDujos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kvadratura1ResDujosActionPerformed(evt);
            }
        });

        kvadratura2ResDujos.setEditable(false);
        kvadratura2ResDujos.setBackground(new java.awt.Color(215, 215, 215));
        kvadratura2ResDujos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Kvadratura2  Dujos:");

        kvadratura3ResDujos.setEditable(false);
        kvadratura3ResDujos.setBackground(new java.awt.Color(215, 215, 215));
        kvadratura3ResDujos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Kvadratura3  Dujos:");

        kvadratura4ResDujos.setEditable(false);
        kvadratura4ResDujos.setBackground(new java.awt.Color(215, 215, 215));
        kvadratura4ResDujos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Kvadratura4  Dujos:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Is viso uz Dujas:");

        resDujosTotal.setEditable(false);
        resDujosTotal.setBackground(new java.awt.Color(215, 215, 215));
        resDujosTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resDujosTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resDujosTotalActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Elektra is viso:");

        elektraTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        elektraTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elektraTotalActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Vanduo is viso:");

        vanduoTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vanduoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vanduoTotalActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Kvadratura 1 su Elektra ir Vandeniu:");

        kvadratura1Total.setEditable(false);
        kvadratura1Total.setBackground(new java.awt.Color(215, 215, 215));
        kvadratura1Total.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kvadratura1Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kvadratura1TotalActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Kvadratura 2 su Elektra ir Vandeniu:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Kvadratura 3 su Elektra ir Vandeniu:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Kvadratura 4 su Elektra ir Vandeniu:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Dujos, Elektra, Vanduo is viso:");

        kvadratura3Total.setEditable(false);
        kvadratura3Total.setBackground(new java.awt.Color(215, 215, 215));
        kvadratura3Total.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kvadratura3Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kvadratura3TotalActionPerformed(evt);
            }
        });

        kvadratura4Total.setEditable(false);
        kvadratura4Total.setBackground(new java.awt.Color(215, 215, 215));
        kvadratura4Total.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kvadratura4Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kvadratura4TotalActionPerformed(evt);
            }
        });

        kvadratura2Total.setEditable(false);
        kvadratura2Total.setBackground(new java.awt.Color(215, 215, 215));
        kvadratura2Total.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kvadratura2Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kvadratura2TotalActionPerformed(evt);
            }
        });

        dujosElektraVanduoTotal.setEditable(false);
        dujosElektraVanduoTotal.setBackground(new java.awt.Color(215, 215, 215));
        dujosElektraVanduoTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dujosElektraVanduoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dujosElektraVanduoTotalActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("€");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("€");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("€");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("€");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("€");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("€");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("€");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("€");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("€");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("€");

        jLabel31.setText("€");

        jLabel32.setText("€");

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("kubiniu metru");

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("€");

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setText("€");

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setText("kv. metru");

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("kv. metru");

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel38.setText("kv. metru");

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setText("kv. metru");

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel40.setText("Dujos Maistui Kepinti ir Troškinti:");
        jLabel40.setToolTipText("");

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(215, 215, 215));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setText("20");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel41.setText("€");

        javax.swing.GroupLayout MokesciaiLayout = new javax.swing.GroupLayout(Mokesciai);
        Mokesciai.setLayout(MokesciaiLayout);
        MokesciaiLayout.setHorizontalGroup(
                MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MokesciaiLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(SkaiciuotiBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(MokesciaiLayout.createSequentialGroup()
                                                .addGroup(MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MokesciaiLayout.createSequentialGroup()
                                                                .addComponent(resDujosTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel25))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MokesciaiLayout.createSequentialGroup()
                                                                .addComponent(kvadratura4ResDujos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel24))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MokesciaiLayout.createSequentialGroup()
                                                                .addComponent(kvadratura3ResDujos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel23))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MokesciaiLayout.createSequentialGroup()
                                                                .addComponent(kvadratura2ResDujos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel22))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MokesciaiLayout.createSequentialGroup()
                                                                .addComponent(kvadratura1ResDujos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel21)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(kvadratura1Total, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(kvadratura2Total, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(kvadratura3Total, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(dujosElektraVanduoTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(kvadratura4Total, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel28)
                                                        .addComponent(jLabel27)
                                                        .addComponent(jLabel26)
                                                        .addComponent(jLabel29)
                                                        .addComponent(jLabel30))
                                                .addGap(51, 51, 51))
                                        .addGroup(MokesciaiLayout.createSequentialGroup()
                                                .addGroup(MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(MokesciaiLayout.createSequentialGroup()
                                                                .addComponent(jLabel40)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                                                        .addGroup(MokesciaiLayout.createSequentialGroup()
                                                                .addGroup(MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                                                                .addGap(1, 1, 1)
                                                                .addGroup(MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(Kvadratura1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(Kvadratura2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(Kvadratura3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(Kvadratura4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(paslaugosMokestis, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(dujuKuboKaina, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(dujuPrinaudota, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(MokesciaiLayout.createSequentialGroup()
                                                                .addGroup(MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(MokesciaiLayout.createSequentialGroup()
                                                                                .addComponent(jLabel39)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(MokesciaiLayout.createSequentialGroup()
                                                                                .addComponent(jLabel38)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(MokesciaiLayout.createSequentialGroup()
                                                                                .addComponent(vanduoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jLabel32))
                                                                        .addGroup(MokesciaiLayout.createSequentialGroup()
                                                                                .addComponent(elektraTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jLabel31))))
                                                        .addComponent(jLabel34)
                                                        .addComponent(jLabel33)
                                                        .addComponent(jLabel35)
                                                        .addComponent(jLabel36)
                                                        .addComponent(jLabel37)
                                                        .addComponent(jLabel41))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        MokesciaiLayout.setVerticalGroup(
                MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MokesciaiLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(Kvadratura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15)
                                        .addComponent(elektraTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel31)
                                        .addComponent(jLabel39))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(Kvadratura2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel16)
                                        .addComponent(vanduoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel32)
                                        .addComponent(jLabel38))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(Kvadratura3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel37))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(Kvadratura4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel36))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(paslaugosMokestis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel35))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(dujuKuboKaina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel34))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(dujuPrinaudota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel33))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(MokesciaiLayout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addGroup(MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel41))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SkaiciuotiBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel6)
                                        .addComponent(kvadratura1Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel21)
                                        .addComponent(kvadratura1ResDujos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel26))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(kvadratura2Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel27))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel17)
                                                .addComponent(jLabel22)
                                                .addComponent(kvadratura2ResDujos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel10)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel18)
                                        .addComponent(kvadratura3Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel23)
                                        .addComponent(kvadratura3ResDujos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel28))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel19)
                                        .addComponent(kvadratura4Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel24)
                                        .addComponent(kvadratura4ResDujos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel29))
                                .addGap(18, 18, 18)
                                .addGroup(MokesciaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel20)
                                        .addComponent(dujosElektraVanduoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel25)
                                        .addComponent(resDujosTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel30))
                                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Mokesciai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Mokesciai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void dujosElektraVanduoTotalActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void kvadratura2TotalActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void kvadratura4TotalActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void kvadratura3TotalActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void kvadratura1TotalActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void vanduoTotalActionPerformed(java.awt.event.ActionEvent evt) {
        vanduoTotal.setForeground(Color.BLACK);
    }

    private void elektraTotalActionPerformed(java.awt.event.ActionEvent evt) {
        elektraTotal.setForeground(Color.BLACK);
    }

    private void resDujosTotalActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void kvadratura1ResDujosActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void SkaiciuotiBtnActionPerformed(java.awt.event.ActionEvent evt) {
        start();
    }

    private void dujuPrinaudotaActionPerformed(java.awt.event.ActionEvent evt) {
        dujuPrinaudota.setForeground(Color.BLACK);
    }

    private void dujuKuboKainaActionPerformed(java.awt.event.ActionEvent evt) {
        dujuKuboKaina.setForeground(Color.BLACK);
    }

    private void paslaugosMokestisActionPerformed(java.awt.event.ActionEvent evt) {
        paslaugosMokestis.setForeground(Color.BLACK);
    }

    private void Kvadratura4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void Kvadratura3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void Kvadratura2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void Kvadratura1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    private void start() {

        validateInput();


        visaKvadratura = parseDouble(Kvadratura1.getText())
                + parseDouble(Kvadratura2.getText())
                + parseDouble(Kvadratura3.getText())
                + parseDouble(Kvadratura4.getText());

        pardavimoMokestis =  parseDouble(paslaugosMokestis.getText());
        double dujosVisos = parseDouble(dujuPrinaudota.getText());
        dujuKaina = parseDouble(dujuKuboKaina.getText());


        dujosMaistuiBendras = 20;
        dujuKainaVisamPlotui = (dujosVisos * dujuKaina)-dujosMaistuiBendras;
        if (dujuKainaVisamPlotui < 1) {
            dujuPrinaudota.setForeground(Color.red);
            dujuKuboKaina.setForeground(Color.red);
            return;
        } else {
            dujuPrinaudota.setForeground(Color.black);
            dujuKuboKaina.setForeground(Color.black);
        }
        dujosMaistuiIndividualus = dujosMaistuiBendras/4;


//9.93, 15.69, 16.44, 22.65
//        double dujos1 = dujuKainaKambariui(10);
//        double dujos2 = dujuKainaKambariui(17);
//        double dujos3 = dujuKainaKambariui(18);
//        double dujos4 = dujuKainaKambariui(24);
        double dujos1 = dujuKainaKambariui(9.93);
        double dujos2 = dujuKainaKambariui(15.69);
        double dujos3 = dujuKainaKambariui(16.44);
        double dujos4 = dujuKainaKambariui(22.65);

        double isVisoDujos = dujos1 + dujos2 + dujos3 + dujos4;


        kvadratura1ResDujos.setText("" + dujos1);
        kvadratura2ResDujos.setText("" + dujos2);
        kvadratura3ResDujos.setText("" + dujos3);
        kvadratura4ResDujos.setText("" + dujos4);
        resDujosTotal.setText("" + apvalint(isVisoDujos,2));


        if (!elektraTotal.getText().equals("") && !vanduoTotal.getText().equals("") ){
            double elektra = parseDouble(elektraTotal.getText());
            double vanduo = parseDouble(vanduoTotal.getText());
            double elektraVanduoIsKeturiu = apvalint((elektra + vanduo) / 4, 2);

            double kvadratu10Total = apvalint(dujos1 + elektraVanduoIsKeturiu,2 );
            double kvadratu15Total = apvalint(dujos2 + elektraVanduoIsKeturiu,2 );
            double kvadratu16Total = apvalint(dujos3 + elektraVanduoIsKeturiu,2 );
            double kvadratu24Total = apvalint(dujos4 + elektraVanduoIsKeturiu,2 );
            double viskas = apvalint(kvadratu10Total + kvadratu15Total + kvadratu16Total + kvadratu24Total,2 );

            kvadratura1Total.setText("" + kvadratu10Total);
            kvadratura2Total.setText("" + kvadratu15Total);
            kvadratura3Total.setText("" + kvadratu16Total);
            kvadratura4Total.setText("" + kvadratu24Total);
            dujosElektraVanduoTotal.setText("" + viskas);

        } else {
            kvadratura1Total.setText("");
            kvadratura2Total.setText("");
            kvadratura3Total.setText("");
            kvadratura4Total.setText("");
            dujosElektraVanduoTotal.setText("");
        }

    }

    public void validateInput() {
        boolean validation1 = true;
        boolean validation2 = true;
        boolean validation3 = true;
        boolean validation4 = true;
        boolean validation5 = true;

        try{
            parseDouble(paslaugosMokestis.getText());
        }
        catch (Exception x){
            validation1 = false;
            paslaugosMokestis.setForeground(Color.red);
        }
        if(validation1){
            paslaugosMokestis.setForeground(Color.black);
        }

        try{
            parseDouble(dujuKuboKaina.getText());
        }
        catch (Exception x){
            validation2 = false;
            dujuKuboKaina.setForeground(Color.red);
        }
        if(validation2){
            dujuKuboKaina.setForeground(Color.black);
        }


        try{
            parseDouble(dujuPrinaudota.getText());
        }
        catch (Exception x){
            validation3 = false;
            dujuPrinaudota.setForeground(Color.red);
        }
        if(validation3){
            dujuPrinaudota.setForeground(Color.black);
        }


        try{
            parseDouble(elektraTotal.getText());
            elektraTotal.setForeground(Color.black);
        }
        catch (Exception x){

            if (!elektraTotal.getText().equals("") && !vanduoTotal.getText().equals("")){
                validation4 = false;
                elektraTotal.setForeground(Color.red);
            } else {
                elektraTotal.setForeground(Color.black);
            }
        }
        try{
            parseDouble(vanduoTotal.getText());
            vanduoTotal.setForeground(Color.black);
        }
        catch (Exception x){

            if (!elektraTotal.getText().equals("") && !vanduoTotal.getText().equals("")){
                validation5 = false;
                vanduoTotal.setForeground(Color.red);
            } else {
                vanduoTotal.setForeground(Color.black);
            }
        }

        if (!validation1 || !validation2 || !validation3  || !validation4 || !validation5 ){
            SkaiciuotiBtn.setForeground(Color.red);
            kvadratura1Total.setText("");
            kvadratura2Total.setText("");
            kvadratura3Total.setText("");
            kvadratura4Total.setText("");
            dujosElektraVanduoTotal.setText("");
            kvadratura1ResDujos.setText("");
            kvadratura2ResDujos.setText("");
            kvadratura3ResDujos.setText("");
            kvadratura4ResDujos.setText("");
            resDujosTotal.setText("");
        } else {
            SkaiciuotiBtn.setForeground(Color.black);
        }


    }

    private double dujosMaistuiBendras;
    private double dujuKainaVisamPlotui;
    private double dujuKaina;
    private double dujosMaistuiIndividualus;
    private double visaKvadratura;
    private double pardavimoMokestis;

    private double dujuKainaKambariui(double kambarioKvadratura) {
        double dujuKainaKambariui =
                (dujuKainaVisamPlotui / visaKvadratura * kambarioKvadratura)
                        + dujosMaistuiBendras / 4
                        + pardavimoMokestis / 4;
        return apvalint(dujuKainaKambariui, 2);
    }

    public static double apvalint(double value, double places) {
        double scale = Math.pow(10, places);
        return Math.round(value * scale) / scale;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mokesciai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mokesciai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mokesciai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mokesciai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mokesciai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JTextField Kvadratura1;
    private javax.swing.JTextField Kvadratura2;
    private javax.swing.JTextField Kvadratura3;
    private javax.swing.JTextField Kvadratura4;
    private javax.swing.JPanel Mokesciai;
    private javax.swing.JButton SkaiciuotiBtn;
    private javax.swing.JTextField dujosElektraVanduoTotal;
    private javax.swing.JTextField dujuKuboKaina;
    private javax.swing.JTextField dujuPrinaudota;
    private javax.swing.JTextField elektraTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField kvadratura1ResDujos;
    private javax.swing.JTextField kvadratura1Total;
    private javax.swing.JTextField kvadratura2ResDujos;
    private javax.swing.JTextField kvadratura2Total;
    private javax.swing.JTextField kvadratura3ResDujos;
    private javax.swing.JTextField kvadratura3Total;
    private javax.swing.JTextField kvadratura4ResDujos;
    private javax.swing.JTextField kvadratura4Total;
    private javax.swing.JTextField paslaugosMokestis;
    private javax.swing.JTextField resDujosTotal;
    private javax.swing.JTextField vanduoTotal;
    // End of variables declaration
}
